name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Merge
        uses: pascalgn/automerge-action@v0.16.2
        if: github.event.pull_request.title == '[pre-commit.ci] pre-commit autoupdate'
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_REMOVE_LABELS: "auto-merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: false
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_DELETE_BRANCH: true
