name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        if: github.event.pull_request.title == '[pre-commit.ci] pre-commit autoupdate'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          -d '{"labels":["automerge"]}'
      - name: Automatic Merge
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
